apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: mavula
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: identity-access-secrets
  namespace: mavula
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: identity-access-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: mavula/identity-access/database_url
    - secretKey: IDENTITY_ISSUER
      remoteRef:
        key: mavula/identity-access/issuer
    - secretKey: IDENTITY_JWKS_JSON
      remoteRef:
        key: mavula/identity-access/private_jwks_json
    - secretKey: IDENTITY_COOKIE_KEYS
      remoteRef:
        key: mavula/identity-access/cookie_keys
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ledger-core-secrets
  namespace: mavula
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: ledger-core-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: mavula/ledger-core/database_url
    - secretKey: OIDC_ISSUER
      remoteRef:
        key: mavula/identity-access/issuer
    - secretKey: OIDC_AUTHORIZATION_ENDPOINT
      remoteRef:
        key: mavula/identity-access/authorization_endpoint
    - secretKey: OIDC_AUDIENCE
      remoteRef:
        key: mavula/ledger-core/audience
    - secretKey: OIDC_JWKS_URI
      remoteRef:
        key: mavula/identity-access/jwks_uri
    - secretKey: REDIS_URL
      remoteRef:
        key: mavula/redis_url
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: workbench-secrets
  namespace: mavula
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: workbench-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: mavula/workbench/database_url
    - secretKey: REDIS_URL
      remoteRef:
        key: mavula/redis_url
    - secretKey: OIDC_ISSUER
      remoteRef:
        key: mavula/identity-access/issuer
    - secretKey: OIDC_AUDIENCE
      remoteRef:
        key: mavula/workbench/audience
    - secretKey: OIDC_JWKS_URI
      remoteRef:
        key: mavula/identity-access/jwks_uri
    - secretKey: OIDC_TOKEN_ENDPOINT
      remoteRef:
        key: mavula/identity-access/token_endpoint
    - secretKey: WORKBENCH_OIDC_CLIENT_ID
      remoteRef:
        key: mavula/workbench/oidc_client_id
    - secretKey: WORKBENCH_PRIVATE_JWK_JSON
      remoteRef:
        key: mavula/workbench/private_client_jwk_json
    - secretKey: LEDGER_CORE_AUDIENCE
      remoteRef:
        key: mavula/ledger-core/audience
