apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: getfluxo
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fengine-secrets
  namespace: getfluxo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: fengine-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: getfluxo/fengine/database_url
    - secretKey: JWT_SECRET
      remoteRef:
        key: getfluxo/fengine/jwt_secret
    - secretKey: REDIS_URL
      remoteRef:
        key: getfluxo/redis_url
    - secretKey: COOKIE_DOMAIN
      remoteRef:
        key: getfluxo/fengine/cookie_domain
    - secretKey: INTERNAL_API_KEY
      remoteRef:
        key: getfluxo/internal_api_key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fwk-secrets
  namespace: getfluxo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: fwk-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: getfluxo/fengine/database_url
    - secretKey: REDIS_URL
      remoteRef:
        key: getfluxo/redis_url
    - secretKey: INTERNAL_API_KEY
      remoteRef:
        key: getfluxo/internal_api_key
