apiVersion: v1
kind: Service
metadata:
  name: workbench
  namespace: mavula
  labels:
    app: workbench
spec:
  selector:
    app: workbench
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3010
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: 3010
  type: ClusterIP
