apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mavula
resources:
  - base/namespace.yaml
  - base/service-identity-access.yaml
  - base/service-ledger-core.yaml
  - base/service-workbench.yaml
  - base/deployment-identity-access.yaml
  - base/deployment-ledger-core.yaml
  - base/deployment-workbench.yaml
  - postgres.yaml
  - redis.yaml
images:
  - name: mavula/identity-access
    newTag: minikube
  - name: mavula/ledger-core
    newTag: minikube
  - name: mavula/workbench
    newTag: minikube
patches:
  - target:
      kind: Deployment
      name: ledger-core
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
  - target:
      kind: Deployment
      name: workbench
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
